server:
  port: 5687
  servlet:
    context-path: /

management:
  endpoint:
    health:
      show-details: "always"
  endpoints:
    web:
      base-path: /
      exposure:
        include: health, info

logging:
  level:
    org:
      springframework: INFO

springdoc:
  packagesToScan: com.mrcorner.journal
  title: jorunal-v1
  description: "Microservice to control all data that is entering the DB"
  writer-with-order-by-keys: true

#If you use a database then uncomment below lines and update db properties accordingly
spring:
  config:
    import: "optional:configtree:/mnt/secrets/${{ values.product }}/"
  application:
    name: journal
  cloud:
    config:
      enabled: false
  profiles:
    active: ${ENVIRONMENT:local}
  main:
    allow-bean-definition-overriding: true
  datasource:
    platform: postgresqllocal
    driver-class-name: org.postgresql.Driver
    url:
    username:
    password:
  jpa:
    show-sql: false
    hibernate.ddl-auto: none
    hibernate.id.new_generator_mappings: true
    hibernate.use-new-id-generator-mappings: true
    hbm2ddl.auto: validate
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        default_schema:
        format_sql: true
        generate_statistics: false
  flyway:
    enabled: true
    url:
    schemas:
    user:
    password:
    validate-on-migrate: false
    baseline-on-migrate: true
    baseline-version: 0